language: python
matrix:
  include:
    - os: windows
      language: sh
      python: 3
      # Perform the manual steps on windows to install python3
      before_install:
        - choco install python3 --params "/InstallDir:C:\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip
        - python -m pip install pywin32
      before_script:
        - export TOXENV=py3-win

    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "nightly"  # 3.10
      before_script:
        - export TOXENV=py310
install:
  - python -m pip install tox
before_script:
  - export TOXENV=$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
script:
  - python -m tox
